"""add_granular_metrics_v2

Revision ID: bb86f3e42f93
Revises: dc6983349dc9
Create Date: 2026-04-07 12:58:24.157594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb86f3e42f93'
down_revision = 'dc6983349dc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_insights', sa.Column('link_clicks', sa.Integer(), nullable=True))
    op.add_column('ad_insights', sa.Column('messages', sa.Integer(), nullable=True))
    op.add_column('ad_insights', sa.Column('leads', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_insights', 'leads')
    op.drop_column('ad_insights', 'messages')
    op.drop_column('ad_insights', 'link_clicks')
    # ### end Alembic commands ###
