"""add_adset_and_ad_columns

Revision ID: da14913bedcf
Revises: 
Create Date: 2026-04-07 12:26:01.964660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da14913bedcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_insights', sa.Column('adset_id', sa.String(), nullable=True))
    op.add_column('ad_insights', sa.Column('adset_name', sa.String(), nullable=True))
    op.add_column('ad_insights', sa.Column('ad_id', sa.String(), nullable=True))
    op.add_column('ad_insights', sa.Column('ad_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_insights', 'ad_name')
    op.drop_column('ad_insights', 'ad_id')
    op.drop_column('ad_insights', 'adset_name')
    op.drop_column('ad_insights', 'adset_id')
    # ### end Alembic commands ###
