"""add_granular_metrics

Revision ID: dc6983349dc9
Revises: da14913bedcf
Create Date: 2026-04-07 12:46:17.813167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6983349dc9'
down_revision = 'da14913bedcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_insights', sa.Column('checkouts_initiated', sa.Integer(), nullable=True))
    op.add_column('ad_insights', sa.Column('purchases', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_insights', 'purchases')
    op.drop_column('ad_insights', 'checkouts_initiated')
    # ### end Alembic commands ###
